# Generated by Django 4.1.2 on 2022-11-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('latitude_deg', models.CharField(max_length=25)),
                ('longitude_deg', models.CharField(max_length=25)),
                ('elevation_ft', models.IntegerField()),
                ('continent', models.CharField(max_length=2)),
                ('iso_country', models.CharField(max_length=2)),
                ('iso_region', models.CharField(max_length=10)),
                ('municipality', models.CharField(max_length=100)),
                ('scheduled_service', models.CharField(max_length=10)),
                ('gps_code', models.CharField(max_length=10)),
                ('iata_code', models.CharField(max_length=3)),
                ('local_code', models.CharField(max_length=10)),
                ('home_link', models.CharField(max_length=150)),
                ('wikipedia_link', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=500)),
            ],
        ),
    ]
