# Generated by Django 4.1.2 on 2022-11-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0002_rename_airportmodel_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='gps_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='home_link',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='keywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='local_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='wikipedia_link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
