# Generated by Django 4.1.2 on 2022-11-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0004_alter_airport_gps_code_alter_airport_home_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='id',
        ),
        migrations.AlterField(
            model_name='airport',
            name='ident',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
