# Generated by Django 4.1.2 on 2022-11-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0005_remove_airport_id_alter_airport_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
