# Generated by Django 4.1.2 on 2022-11-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airports', '0006_airport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
